# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6a135d72f846586cff7ef3fe0f9b927d"
name = "remix-testing"
handle = "remix-testing-3"
application_url = "https://chest-charms-faces-seasons.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mort-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_product_listings,write_products"

[auth]
redirect_urls = [
  "https://chest-charms-faces-seasons.trycloudflare.com/auth/callback",
  "https://chest-charms-faces-seasons.trycloudflare.com/auth/shopify/callback",
  "https://chest-charms-faces-seasons.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
